###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

Simple exploration of aircrafts types in the database

**Install the following packages:**

In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /home/alejand/environments/courses/lib/python3.8/site-packages (8.0.22)
Requirement already satisfied: protobuf>=3.0.0 in /home/alejand/environments/courses/lib/python3.8/site-packages (from mysql-connector-python) (3.14.0)
Requirement already satisfied: six>=1.9 in /home/alejand/environments/courses/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)

In [2]:
import mysql.connector
import pandas as pd

In [3]:
# Connect to DB
mydb = mysql.connector.connect(
    host = "localhost",
    user = "root",
    passwd = "cuba",
    database = "airnoise"
)
dbcursor = mydb.cursor()

In [4]:
sql = '''SELECT a.id_aircraft, a.identifier, COUNT(m.aircraft) AS observations, a.description
FROM measurements m, aircrafts a WHERE a.id_aircraft = m.aircraft AND m.quality IN (1,2,3)
GROUP BY m.aircraft ORDER BY observations DESC;'''

dbcursor.execute(sql)
results = dbcursor.fetchall()
df = pd.DataFrame(results,columns =['aircraft', 'identifier', 'observations','description'])
df

,aircraft,identifier,observations,description
0,1,A320-2xx (CFM56-5),39,In the ANP the A320-211 is in the acoustic cla...
1,10,B737-7xx (CF56-7B22-),27,In the ANP both 737-700 and 737-800 are mapped...
2,13,ERJ190 (CF34-10E),22,It does not appear in the ANP.
3,9,B737-8xx (CF56-7B22+),19,In the ANP both 737-700 and 737-800 are mapped...
4,11,ERJ145 (AE3007),18,In the ANP both EMB145 and EMB14L are mapped t...
5,2,A320-2xx (V25xx),11,In the ANP the A320-232 is in the acoustic cla...
6,4,A319-1xx (V25xx),10,In the ANP appears the A319-131 with V2522-A5 ...
7,6,ATR42-500 (PW127E),8,It does not appear in the ANP.
8,12,ERJ170/175 (CF34-8E),8,It does not appear in the ANP.
9,8,B737-3xx (CFM56-3),8,In the ANP both 737-300 and 737-3B2 appear in ...
10,7,ATR72-600 (PW127M),3,It does not appear in the ANP.
11,16,SU95 (SaM 146),3,It does not appear in the ANP. Sukoi.
12,15,TU204 (PS-90A),2,It does not appear in the ANP.
13,5,ATR42-300 (PW120),2,In the ANP it does not appear but there is a c...
14,3,A319-1xx (CFM56-5),1,In the ANP only the A319-131 with V2522-A5 eng...
15,14,MD-8x (2JT8D2),1,"In the ANP aircrafts MD81, MD82 and MD83 are g..."
16,17,787-8 Dreamliner (GEnx-1B),1,It does not appear in the ANP.
17,18,B767-3* (PW4060),1,In the ANP appears in the acoustic class 2CF680.
18,19,B747-8* (GEnx-2B67),1,It does not appear in the ANP.
19,20,B747-4*(CF6-80C2B5F),1,It does not appear in the ANP.
20,21,CRJ200 (CF34-3B1),1,It does not appear in the ANP.

In [5]:
sql = '''SELECT a.id_aircraft, a.identifier, COUNT(m.aircraft) AS observations, a.description
FROM measurements m, aircrafts a WHERE a.id_aircraft = m.aircraft AND m.quality IN (1,2)
GROUP BY m.aircraft ORDER BY observations DESC;'''

dbcursor.execute(sql)
results = dbcursor.fetchall()
df = pd.DataFrame(results,columns =['aircraft', 'identifier', 'observations','description'])
df

,aircraft,identifier,observations,description
0,1,A320-2xx (CFM56-5),39,In the ANP the A320-211 is in the acoustic cla...
1,10,B737-7xx (CF56-7B22-),19,In the ANP both 737-700 and 737-800 are mapped...
2,9,B737-8xx (CF56-7B22+),17,In the ANP both 737-700 and 737-800 are mapped...
3,13,ERJ190 (CF34-10E),15,It does not appear in the ANP.
4,11,ERJ145 (AE3007),11,In the ANP both EMB145 and EMB14L are mapped t...
5,2,A320-2xx (V25xx),11,In the ANP the A320-232 is in the acoustic cla...
6,4,A319-1xx (V25xx),9,In the ANP appears the A319-131 with V2522-A5 ...
7,12,ERJ170/175 (CF34-8E),8,It does not appear in the ANP.
8,8,B737-3xx (CFM56-3),7,In the ANP both 737-300 and 737-3B2 appear in ...
9,6,ATR42-500 (PW127E),6,It does not appear in the ANP.
10,7,ATR72-600 (PW127M),3,It does not appear in the ANP.
11,16,SU95 (SaM 146),3,It does not appear in the ANP. Sukoi.
12,15,TU204 (PS-90A),2,It does not appear in the ANP.
13,3,A319-1xx (CFM56-5),1,In the ANP only the A319-131 with V2522-A5 eng...
14,5,ATR42-300 (PW120),1,In the ANP it does not appear but there is a c...
15,14,MD-8x (2JT8D2),1,"In the ANP aircrafts MD81, MD82 and MD83 are g..."
16,17,787-8 Dreamliner (GEnx-1B),1,It does not appear in the ANP.
17,18,B767-3* (PW4060),1,In the ANP appears in the acoustic class 2CF680.
18,19,B747-8* (GEnx-2B67),1,It does not appear in the ANP.
19,20,B747-4*(CF6-80C2B5F),1,It does not appear in the ANP.